name: Validate PR

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Validate token list
        run: yarn validate